VERSION --raw-output 0.8
PROJECT jahands/docker

build:
	FROM --pass-args ../debian/+debian-12-slim
	RUN apt-get update && \
		apt-get install -y unzip && \
		rm -rf /var/lib/apt/lists/*
	RUN curl https://sh.uuid.rocks/install/rclone | bash
	CMD ["rclone"]

	COPY (../common+version/VERSION --package=docker/rclone) .
	LET docker_tag=$(cat ./VERSION)
	IF [ -z "$docker_tag" ]
		# SAVE IMAGE --push gitea.uuid.rocks/geobox/rclone:nightly
	ELSE
		SAVE IMAGE --push gitea.uuid.rocks/geobox/rclone:$docker_tag \
											gitea.uuid.rocks/geobox/rclone:latest
	END
