VERSION --raw-output 0.8
PROJECT jahands/docker

version:
	FROM alpine:3
	COPY (../common+version/VERSION --package=docker/debian) .
	SAVE ARTIFACT ./VERSION

debian-12-slim:
	FROM debian:12-slim
	RUN apt-get update \
		&& apt-get install -y curl \
		&& rm -rf /var/lib/apt/lists/*
	RUN curl -fsSL https://sh.uuid.rocks/install/wcurl | bash

	CMD ["sleep", "infinity"]

	COPY +version/VERSION .
	LET docker_tag=$(cat ./VERSION)
	IF [ -z "$docker_tag" ]
		# SAVE IMAGE --push gitea.uuid.rocks/geobox/debian:12-slim-nightly
	ELSE
		SAVE IMAGE --push gitea.uuid.rocks/geobox/debian:12-slim-$docker_tag \
											gitea.uuid.rocks/geobox/debian:12-slim \
											gitea.uuid.rocks/geobox/debian:latest
	END

build:
	BUILD +debian-12-slim
