name: Astroblog

# Triggered by a request from my private Ghost instance
on:
  repository_dispatch:

env:
  FORCE_COLOR: 1

jobs:
  deploy:
    name: Deploy Astroblog
    runs-on: ubicloud-standard-2
    timeout-minutes: 10
    concurrency: workers-monorepo-deploy
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      EARTHLY_ORG: jahands
      EARTHLY_SATELLITE: mini-sat
    steps:
      - uses: earthly/actions-setup@v1.0.13
        with:
          version: v0.8.15
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 20
      - name: Deploy
        run: earthly --ci --push +deploy-astroblog --GITHUB_ACTIONS=1
